/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:965d5f03-946e-4cd7-b7d5-2e7df2a06192",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dcoRXfUpp",
    "aws_user_pools_web_client_id": "47l18d45s6madj2nnn2231o06d",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "GIVEN_NAME",
        "FAMILY_NAME",
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "ON",
    "aws_cognito_mfa_types": [
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ae7mccx4ffcl7ivzob5azj2gn4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qrozkp7s3nbd3kbixmfjfqxo3i",
    "aws_mobile_analytics_app_id": "a53ab95b569d4a998bf661bba39f246b",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "a53ab95b569d4a998bf661bba39f246b",
            "region": "us-east-1"
        }
    },
    "Notifications": {
        "InAppMessaging": {
            "AWSPinpoint": {
                "appId": "a53ab95b569d4a998bf661bba39f246b",
                "region": "us-east-1"
            }
        }
    }
};


export default awsmobile;
